name: Build Spring Boot app with Maven

on:
  push:
    branches: [master]

jobs:
  hello:
    runs-on: ubuntu-22.04

    steps:
      # 가상머신에 소스코드 다운로드
      - name: Checkout code
        uses: actions/checkout@v3

      # JDK 17 설치
      - name: set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # maven으로 자바 프로젝트 빌드
      - name: build with maven
        run: mvn -B package --file pom.xml -DskipTests

      # 빌드한 결과물 확인
      - name: list target directory
        run: ls -la target

